language: python
python:
    - "3.7.3"
    
before_install:
  - brew update > /dev/null
  - brew cask install google-chrome

install:
    pip install -r requirements.txt

script:
    - pytest -s test.py
